/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProprietaireIndexRouteImport } from './routes/proprietaire/index'
import { Route as ProprietaireProprietaireLayoutRouteImport } from './routes/proprietaire/_proprietaireLayout'
import { Route as LocataireLocataireLayoutRouteImport } from './routes/locataire/_locataireLayout'
import { Route as AuthAuthLayoutRouteImport } from './routes/auth/_authLayout'
import { Route as visiteurGuestLayoutRouteImport } from './routes/(visiteur)/_guestLayout'
import { Route as LocataireLocataireLayoutIndexRouteImport } from './routes/locataire/_locataireLayout/index'
import { Route as visiteurGuestLayoutIndexRouteImport } from './routes/(visiteur)/_guestLayout/index'
import { Route as ProprietaireProprietaireLayoutDashboardRouteImport } from './routes/proprietaire/_proprietaireLayout/dashboard'
import { Route as LocataireLocataireLayoutDashboardRouteImport } from './routes/locataire/_locataireLayout/dashboard'
import { Route as AuthAuthLayoutRegisterRouteImport } from './routes/auth/_authLayout/register'
import { Route as AuthAuthLayoutLoginRouteImport } from './routes/auth/_authLayout/login'
import { Route as visiteurGuestLayoutLocationRouteImport } from './routes/(visiteur)/_guestLayout/location'
import { Route as ProprietaireProprietaireLayoutRendezVousIndexRouteImport } from './routes/proprietaire/_proprietaireLayout/rendez-vous/index'
import { Route as ProprietaireProprietaireLayoutPaiementsIndexRouteImport } from './routes/proprietaire/_proprietaireLayout/paiements/index'
import { Route as ProprietaireProprietaireLayoutMaisonsIndexRouteImport } from './routes/proprietaire/_proprietaireLayout/maisons/index'
import { Route as ProprietaireProprietaireLayoutContratsIndexRouteImport } from './routes/proprietaire/_proprietaireLayout/contrats/index'
import { Route as ProprietaireProprietaireLayoutChambresIndexRouteImport } from './routes/proprietaire/_proprietaireLayout/chambres/index'
import { Route as LocataireLocataireLayoutRendezVousIndexRouteImport } from './routes/locataire/_locataireLayout/rendez-vous/index'
import { Route as LocataireLocataireLayoutContratsIndexRouteImport } from './routes/locataire/_locataireLayout/contrats/index'
import { Route as ProprietaireProprietaireLayoutRendezVousRendezVousIdIndexRouteImport } from './routes/proprietaire/_proprietaireLayout/rendez-vous/$rendezVousId/index'
import { Route as ProprietaireProprietaireLayoutPaiementsPaiementIdIndexRouteImport } from './routes/proprietaire/_proprietaireLayout/paiements/$paiementId/index'
import { Route as ProprietaireProprietaireLayoutMaisonsMaisonIdIndexRouteImport } from './routes/proprietaire/_proprietaireLayout/maisons/$maisonId/index'
import { Route as ProprietaireProprietaireLayoutContratsContratIdIndexRouteImport } from './routes/proprietaire/_proprietaireLayout/contrats/$contratId/index'
import { Route as ProprietaireProprietaireLayoutChambresChambreIdIndexRouteImport } from './routes/proprietaire/_proprietaireLayout/chambres/$chambreId/index'
import { Route as LocataireLocataireLayoutRendezVousRendezVousIdIndexRouteImport } from './routes/locataire/_locataireLayout/rendez-vous/$rendezVousId/index'
import { Route as LocataireLocataireLayoutContratsContratIdIndexRouteImport } from './routes/locataire/_locataireLayout/contrats/$contratId/index'
import { Route as visiteurGuestLayoutChambreChambreIdIndexRouteImport } from './routes/(visiteur)/_guestLayout/chambre.$chambreId/index'

const ProprietaireRouteImport = createFileRoute('/proprietaire')()
const LocataireRouteImport = createFileRoute('/locataire')()
const AuthRouteImport = createFileRoute('/auth')()
const visiteurRouteImport = createFileRoute('/(visiteur)')()
const ProprietaireProprietaireLayoutProfileLazyRouteImport = createFileRoute(
  '/proprietaire/_proprietaireLayout/profile',
)()
const LocataireLocataireLayoutProfileLazyRouteImport = createFileRoute(
  '/locataire/_locataireLayout/profile',
)()

const ProprietaireRoute = ProprietaireRouteImport.update({
  id: '/proprietaire',
  path: '/proprietaire',
  getParentRoute: () => rootRouteImport,
} as any)
const LocataireRoute = LocataireRouteImport.update({
  id: '/locataire',
  path: '/locataire',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const visiteurRoute = visiteurRouteImport.update({
  id: '/(visiteur)',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietaireIndexRoute = ProprietaireIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProprietaireRoute,
} as any)
const ProprietaireProprietaireLayoutRoute =
  ProprietaireProprietaireLayoutRouteImport.update({
    id: '/_proprietaireLayout',
    getParentRoute: () => ProprietaireRoute,
  } as any)
const LocataireLocataireLayoutRoute =
  LocataireLocataireLayoutRouteImport.update({
    id: '/_locataireLayout',
    getParentRoute: () => LocataireRoute,
  } as any)
const AuthAuthLayoutRoute = AuthAuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => AuthRoute,
} as any)
const visiteurGuestLayoutRoute = visiteurGuestLayoutRouteImport.update({
  id: '/_guestLayout',
  getParentRoute: () => visiteurRoute,
} as any)
const LocataireLocataireLayoutIndexRoute =
  LocataireLocataireLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocataireLocataireLayoutRoute,
  } as any)
const visiteurGuestLayoutIndexRoute =
  visiteurGuestLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => visiteurGuestLayoutRoute,
  } as any)
const ProprietaireProprietaireLayoutProfileLazyRoute =
  ProprietaireProprietaireLayoutProfileLazyRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any).lazy(() =>
    import('./routes/proprietaire/_proprietaireLayout/profile.lazy').then(
      (d) => d.Route,
    ),
  )
const LocataireLocataireLayoutProfileLazyRoute =
  LocataireLocataireLayoutProfileLazyRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LocataireLocataireLayoutRoute,
  } as any).lazy(() =>
    import('./routes/locataire/_locataireLayout/profile.lazy').then(
      (d) => d.Route,
    ),
  )
const ProprietaireProprietaireLayoutDashboardRoute =
  ProprietaireProprietaireLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any)
const LocataireLocataireLayoutDashboardRoute =
  LocataireLocataireLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LocataireLocataireLayoutRoute,
  } as any)
const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const visiteurGuestLayoutLocationRoute =
  visiteurGuestLayoutLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => visiteurGuestLayoutRoute,
  } as any)
const ProprietaireProprietaireLayoutRendezVousIndexRoute =
  ProprietaireProprietaireLayoutRendezVousIndexRouteImport.update({
    id: '/rendez-vous/',
    path: '/rendez-vous/',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any)
const ProprietaireProprietaireLayoutPaiementsIndexRoute =
  ProprietaireProprietaireLayoutPaiementsIndexRouteImport.update({
    id: '/paiements/',
    path: '/paiements/',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any)
const ProprietaireProprietaireLayoutMaisonsIndexRoute =
  ProprietaireProprietaireLayoutMaisonsIndexRouteImport.update({
    id: '/maisons/',
    path: '/maisons/',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any)
const ProprietaireProprietaireLayoutContratsIndexRoute =
  ProprietaireProprietaireLayoutContratsIndexRouteImport.update({
    id: '/contrats/',
    path: '/contrats/',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any)
const ProprietaireProprietaireLayoutChambresIndexRoute =
  ProprietaireProprietaireLayoutChambresIndexRouteImport.update({
    id: '/chambres/',
    path: '/chambres/',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any)
const LocataireLocataireLayoutRendezVousIndexRoute =
  LocataireLocataireLayoutRendezVousIndexRouteImport.update({
    id: '/rendez-vous/',
    path: '/rendez-vous/',
    getParentRoute: () => LocataireLocataireLayoutRoute,
  } as any)
const LocataireLocataireLayoutContratsIndexRoute =
  LocataireLocataireLayoutContratsIndexRouteImport.update({
    id: '/contrats/',
    path: '/contrats/',
    getParentRoute: () => LocataireLocataireLayoutRoute,
  } as any)
const ProprietaireProprietaireLayoutRendezVousRendezVousIdIndexRoute =
  ProprietaireProprietaireLayoutRendezVousRendezVousIdIndexRouteImport.update({
    id: '/rendez-vous/$rendezVousId/',
    path: '/rendez-vous/$rendezVousId/',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any)
const ProprietaireProprietaireLayoutPaiementsPaiementIdIndexRoute =
  ProprietaireProprietaireLayoutPaiementsPaiementIdIndexRouteImport.update({
    id: '/paiements/$paiementId/',
    path: '/paiements/$paiementId/',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any)
const ProprietaireProprietaireLayoutMaisonsMaisonIdIndexRoute =
  ProprietaireProprietaireLayoutMaisonsMaisonIdIndexRouteImport.update({
    id: '/maisons/$maisonId/',
    path: '/maisons/$maisonId/',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any)
const ProprietaireProprietaireLayoutContratsContratIdIndexRoute =
  ProprietaireProprietaireLayoutContratsContratIdIndexRouteImport.update({
    id: '/contrats/$contratId/',
    path: '/contrats/$contratId/',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any)
const ProprietaireProprietaireLayoutChambresChambreIdIndexRoute =
  ProprietaireProprietaireLayoutChambresChambreIdIndexRouteImport.update({
    id: '/chambres/$chambreId/',
    path: '/chambres/$chambreId/',
    getParentRoute: () => ProprietaireProprietaireLayoutRoute,
  } as any)
const LocataireLocataireLayoutRendezVousRendezVousIdIndexRoute =
  LocataireLocataireLayoutRendezVousRendezVousIdIndexRouteImport.update({
    id: '/rendez-vous/$rendezVousId/',
    path: '/rendez-vous/$rendezVousId/',
    getParentRoute: () => LocataireLocataireLayoutRoute,
  } as any)
const LocataireLocataireLayoutContratsContratIdIndexRoute =
  LocataireLocataireLayoutContratsContratIdIndexRouteImport.update({
    id: '/contrats/$contratId/',
    path: '/contrats/$contratId/',
    getParentRoute: () => LocataireLocataireLayoutRoute,
  } as any)
const visiteurGuestLayoutChambreChambreIdIndexRoute =
  visiteurGuestLayoutChambreChambreIdIndexRouteImport.update({
    id: '/chambre/$chambreId/',
    path: '/chambre/$chambreId/',
    getParentRoute: () => visiteurGuestLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof visiteurGuestLayoutIndexRoute
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/locataire': typeof LocataireLocataireLayoutRouteWithChildren
  '/proprietaire': typeof ProprietaireProprietaireLayoutRouteWithChildren
  '/proprietaire/': typeof ProprietaireIndexRoute
  '/location': typeof visiteurGuestLayoutLocationRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/locataire/dashboard': typeof LocataireLocataireLayoutDashboardRoute
  '/proprietaire/dashboard': typeof ProprietaireProprietaireLayoutDashboardRoute
  '/locataire/profile': typeof LocataireLocataireLayoutProfileLazyRoute
  '/proprietaire/profile': typeof ProprietaireProprietaireLayoutProfileLazyRoute
  '/locataire/': typeof LocataireLocataireLayoutIndexRoute
  '/locataire/contrats': typeof LocataireLocataireLayoutContratsIndexRoute
  '/locataire/rendez-vous': typeof LocataireLocataireLayoutRendezVousIndexRoute
  '/proprietaire/chambres': typeof ProprietaireProprietaireLayoutChambresIndexRoute
  '/proprietaire/contrats': typeof ProprietaireProprietaireLayoutContratsIndexRoute
  '/proprietaire/maisons': typeof ProprietaireProprietaireLayoutMaisonsIndexRoute
  '/proprietaire/paiements': typeof ProprietaireProprietaireLayoutPaiementsIndexRoute
  '/proprietaire/rendez-vous': typeof ProprietaireProprietaireLayoutRendezVousIndexRoute
  '/chambre/$chambreId': typeof visiteurGuestLayoutChambreChambreIdIndexRoute
  '/locataire/contrats/$contratId': typeof LocataireLocataireLayoutContratsContratIdIndexRoute
  '/locataire/rendez-vous/$rendezVousId': typeof LocataireLocataireLayoutRendezVousRendezVousIdIndexRoute
  '/proprietaire/chambres/$chambreId': typeof ProprietaireProprietaireLayoutChambresChambreIdIndexRoute
  '/proprietaire/contrats/$contratId': typeof ProprietaireProprietaireLayoutContratsContratIdIndexRoute
  '/proprietaire/maisons/$maisonId': typeof ProprietaireProprietaireLayoutMaisonsMaisonIdIndexRoute
  '/proprietaire/paiements/$paiementId': typeof ProprietaireProprietaireLayoutPaiementsPaiementIdIndexRoute
  '/proprietaire/rendez-vous/$rendezVousId': typeof ProprietaireProprietaireLayoutRendezVousRendezVousIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/locataire': typeof LocataireLocataireLayoutIndexRoute
  '/proprietaire': typeof ProprietaireIndexRoute
  '/location': typeof visiteurGuestLayoutLocationRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/locataire/dashboard': typeof LocataireLocataireLayoutDashboardRoute
  '/proprietaire/dashboard': typeof ProprietaireProprietaireLayoutDashboardRoute
  '/locataire/profile': typeof LocataireLocataireLayoutProfileLazyRoute
  '/proprietaire/profile': typeof ProprietaireProprietaireLayoutProfileLazyRoute
  '/': typeof visiteurGuestLayoutIndexRoute
  '/locataire/contrats': typeof LocataireLocataireLayoutContratsIndexRoute
  '/locataire/rendez-vous': typeof LocataireLocataireLayoutRendezVousIndexRoute
  '/proprietaire/chambres': typeof ProprietaireProprietaireLayoutChambresIndexRoute
  '/proprietaire/contrats': typeof ProprietaireProprietaireLayoutContratsIndexRoute
  '/proprietaire/maisons': typeof ProprietaireProprietaireLayoutMaisonsIndexRoute
  '/proprietaire/paiements': typeof ProprietaireProprietaireLayoutPaiementsIndexRoute
  '/proprietaire/rendez-vous': typeof ProprietaireProprietaireLayoutRendezVousIndexRoute
  '/chambre/$chambreId': typeof visiteurGuestLayoutChambreChambreIdIndexRoute
  '/locataire/contrats/$contratId': typeof LocataireLocataireLayoutContratsContratIdIndexRoute
  '/locataire/rendez-vous/$rendezVousId': typeof LocataireLocataireLayoutRendezVousRendezVousIdIndexRoute
  '/proprietaire/chambres/$chambreId': typeof ProprietaireProprietaireLayoutChambresChambreIdIndexRoute
  '/proprietaire/contrats/$contratId': typeof ProprietaireProprietaireLayoutContratsContratIdIndexRoute
  '/proprietaire/maisons/$maisonId': typeof ProprietaireProprietaireLayoutMaisonsMaisonIdIndexRoute
  '/proprietaire/paiements/$paiementId': typeof ProprietaireProprietaireLayoutPaiementsPaiementIdIndexRoute
  '/proprietaire/rendez-vous/$rendezVousId': typeof ProprietaireProprietaireLayoutRendezVousRendezVousIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(visiteur)': typeof visiteurRouteWithChildren
  '/(visiteur)/_guestLayout': typeof visiteurGuestLayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_authLayout': typeof AuthAuthLayoutRouteWithChildren
  '/locataire': typeof LocataireRouteWithChildren
  '/locataire/_locataireLayout': typeof LocataireLocataireLayoutRouteWithChildren
  '/proprietaire': typeof ProprietaireRouteWithChildren
  '/proprietaire/_proprietaireLayout': typeof ProprietaireProprietaireLayoutRouteWithChildren
  '/proprietaire/': typeof ProprietaireIndexRoute
  '/(visiteur)/_guestLayout/location': typeof visiteurGuestLayoutLocationRoute
  '/auth/_authLayout/login': typeof AuthAuthLayoutLoginRoute
  '/auth/_authLayout/register': typeof AuthAuthLayoutRegisterRoute
  '/locataire/_locataireLayout/dashboard': typeof LocataireLocataireLayoutDashboardRoute
  '/proprietaire/_proprietaireLayout/dashboard': typeof ProprietaireProprietaireLayoutDashboardRoute
  '/locataire/_locataireLayout/profile': typeof LocataireLocataireLayoutProfileLazyRoute
  '/proprietaire/_proprietaireLayout/profile': typeof ProprietaireProprietaireLayoutProfileLazyRoute
  '/(visiteur)/_guestLayout/': typeof visiteurGuestLayoutIndexRoute
  '/locataire/_locataireLayout/': typeof LocataireLocataireLayoutIndexRoute
  '/locataire/_locataireLayout/contrats/': typeof LocataireLocataireLayoutContratsIndexRoute
  '/locataire/_locataireLayout/rendez-vous/': typeof LocataireLocataireLayoutRendezVousIndexRoute
  '/proprietaire/_proprietaireLayout/chambres/': typeof ProprietaireProprietaireLayoutChambresIndexRoute
  '/proprietaire/_proprietaireLayout/contrats/': typeof ProprietaireProprietaireLayoutContratsIndexRoute
  '/proprietaire/_proprietaireLayout/maisons/': typeof ProprietaireProprietaireLayoutMaisonsIndexRoute
  '/proprietaire/_proprietaireLayout/paiements/': typeof ProprietaireProprietaireLayoutPaiementsIndexRoute
  '/proprietaire/_proprietaireLayout/rendez-vous/': typeof ProprietaireProprietaireLayoutRendezVousIndexRoute
  '/(visiteur)/_guestLayout/chambre/$chambreId/': typeof visiteurGuestLayoutChambreChambreIdIndexRoute
  '/locataire/_locataireLayout/contrats/$contratId/': typeof LocataireLocataireLayoutContratsContratIdIndexRoute
  '/locataire/_locataireLayout/rendez-vous/$rendezVousId/': typeof LocataireLocataireLayoutRendezVousRendezVousIdIndexRoute
  '/proprietaire/_proprietaireLayout/chambres/$chambreId/': typeof ProprietaireProprietaireLayoutChambresChambreIdIndexRoute
  '/proprietaire/_proprietaireLayout/contrats/$contratId/': typeof ProprietaireProprietaireLayoutContratsContratIdIndexRoute
  '/proprietaire/_proprietaireLayout/maisons/$maisonId/': typeof ProprietaireProprietaireLayoutMaisonsMaisonIdIndexRoute
  '/proprietaire/_proprietaireLayout/paiements/$paiementId/': typeof ProprietaireProprietaireLayoutPaiementsPaiementIdIndexRoute
  '/proprietaire/_proprietaireLayout/rendez-vous/$rendezVousId/': typeof ProprietaireProprietaireLayoutRendezVousRendezVousIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/locataire'
    | '/proprietaire'
    | '/proprietaire/'
    | '/location'
    | '/auth/login'
    | '/auth/register'
    | '/locataire/dashboard'
    | '/proprietaire/dashboard'
    | '/locataire/profile'
    | '/proprietaire/profile'
    | '/locataire/'
    | '/locataire/contrats'
    | '/locataire/rendez-vous'
    | '/proprietaire/chambres'
    | '/proprietaire/contrats'
    | '/proprietaire/maisons'
    | '/proprietaire/paiements'
    | '/proprietaire/rendez-vous'
    | '/chambre/$chambreId'
    | '/locataire/contrats/$contratId'
    | '/locataire/rendez-vous/$rendezVousId'
    | '/proprietaire/chambres/$chambreId'
    | '/proprietaire/contrats/$contratId'
    | '/proprietaire/maisons/$maisonId'
    | '/proprietaire/paiements/$paiementId'
    | '/proprietaire/rendez-vous/$rendezVousId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/locataire'
    | '/proprietaire'
    | '/location'
    | '/auth/login'
    | '/auth/register'
    | '/locataire/dashboard'
    | '/proprietaire/dashboard'
    | '/locataire/profile'
    | '/proprietaire/profile'
    | '/'
    | '/locataire/contrats'
    | '/locataire/rendez-vous'
    | '/proprietaire/chambres'
    | '/proprietaire/contrats'
    | '/proprietaire/maisons'
    | '/proprietaire/paiements'
    | '/proprietaire/rendez-vous'
    | '/chambre/$chambreId'
    | '/locataire/contrats/$contratId'
    | '/locataire/rendez-vous/$rendezVousId'
    | '/proprietaire/chambres/$chambreId'
    | '/proprietaire/contrats/$contratId'
    | '/proprietaire/maisons/$maisonId'
    | '/proprietaire/paiements/$paiementId'
    | '/proprietaire/rendez-vous/$rendezVousId'
  id:
    | '__root__'
    | '/(visiteur)'
    | '/(visiteur)/_guestLayout'
    | '/auth'
    | '/auth/_authLayout'
    | '/locataire'
    | '/locataire/_locataireLayout'
    | '/proprietaire'
    | '/proprietaire/_proprietaireLayout'
    | '/proprietaire/'
    | '/(visiteur)/_guestLayout/location'
    | '/auth/_authLayout/login'
    | '/auth/_authLayout/register'
    | '/locataire/_locataireLayout/dashboard'
    | '/proprietaire/_proprietaireLayout/dashboard'
    | '/locataire/_locataireLayout/profile'
    | '/proprietaire/_proprietaireLayout/profile'
    | '/(visiteur)/_guestLayout/'
    | '/locataire/_locataireLayout/'
    | '/locataire/_locataireLayout/contrats/'
    | '/locataire/_locataireLayout/rendez-vous/'
    | '/proprietaire/_proprietaireLayout/chambres/'
    | '/proprietaire/_proprietaireLayout/contrats/'
    | '/proprietaire/_proprietaireLayout/maisons/'
    | '/proprietaire/_proprietaireLayout/paiements/'
    | '/proprietaire/_proprietaireLayout/rendez-vous/'
    | '/(visiteur)/_guestLayout/chambre/$chambreId/'
    | '/locataire/_locataireLayout/contrats/$contratId/'
    | '/locataire/_locataireLayout/rendez-vous/$rendezVousId/'
    | '/proprietaire/_proprietaireLayout/chambres/$chambreId/'
    | '/proprietaire/_proprietaireLayout/contrats/$contratId/'
    | '/proprietaire/_proprietaireLayout/maisons/$maisonId/'
    | '/proprietaire/_proprietaireLayout/paiements/$paiementId/'
    | '/proprietaire/_proprietaireLayout/rendez-vous/$rendezVousId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  visiteurRoute: typeof visiteurRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LocataireRoute: typeof LocataireRouteWithChildren
  ProprietaireRoute: typeof ProprietaireRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proprietaire': {
      id: '/proprietaire'
      path: '/proprietaire'
      fullPath: '/proprietaire'
      preLoaderRoute: typeof ProprietaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locataire': {
      id: '/locataire'
      path: '/locataire'
      fullPath: '/locataire'
      preLoaderRoute: typeof LocataireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visiteur)': {
      id: '/(visiteur)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof visiteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietaire/': {
      id: '/proprietaire/'
      path: '/'
      fullPath: '/proprietaire/'
      preLoaderRoute: typeof ProprietaireIndexRouteImport
      parentRoute: typeof ProprietaireRoute
    }
    '/proprietaire/_proprietaireLayout': {
      id: '/proprietaire/_proprietaireLayout'
      path: '/proprietaire'
      fullPath: '/proprietaire'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutRouteImport
      parentRoute: typeof ProprietaireRoute
    }
    '/locataire/_locataireLayout': {
      id: '/locataire/_locataireLayout'
      path: '/locataire'
      fullPath: '/locataire'
      preLoaderRoute: typeof LocataireLocataireLayoutRouteImport
      parentRoute: typeof LocataireRoute
    }
    '/auth/_authLayout': {
      id: '/auth/_authLayout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(visiteur)/_guestLayout': {
      id: '/(visiteur)/_guestLayout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof visiteurGuestLayoutRouteImport
      parentRoute: typeof visiteurRoute
    }
    '/locataire/_locataireLayout/': {
      id: '/locataire/_locataireLayout/'
      path: '/'
      fullPath: '/locataire/'
      preLoaderRoute: typeof LocataireLocataireLayoutIndexRouteImport
      parentRoute: typeof LocataireLocataireLayoutRoute
    }
    '/(visiteur)/_guestLayout/': {
      id: '/(visiteur)/_guestLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof visiteurGuestLayoutIndexRouteImport
      parentRoute: typeof visiteurGuestLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/profile': {
      id: '/proprietaire/_proprietaireLayout/profile'
      path: '/profile'
      fullPath: '/proprietaire/profile'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutProfileLazyRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/locataire/_locataireLayout/profile': {
      id: '/locataire/_locataireLayout/profile'
      path: '/profile'
      fullPath: '/locataire/profile'
      preLoaderRoute: typeof LocataireLocataireLayoutProfileLazyRouteImport
      parentRoute: typeof LocataireLocataireLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/dashboard': {
      id: '/proprietaire/_proprietaireLayout/dashboard'
      path: '/dashboard'
      fullPath: '/proprietaire/dashboard'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutDashboardRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/locataire/_locataireLayout/dashboard': {
      id: '/locataire/_locataireLayout/dashboard'
      path: '/dashboard'
      fullPath: '/locataire/dashboard'
      preLoaderRoute: typeof LocataireLocataireLayoutDashboardRouteImport
      parentRoute: typeof LocataireLocataireLayoutRoute
    }
    '/auth/_authLayout/register': {
      id: '/auth/_authLayout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthLayoutRegisterRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/auth/_authLayout/login': {
      id: '/auth/_authLayout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLayoutLoginRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/(visiteur)/_guestLayout/location': {
      id: '/(visiteur)/_guestLayout/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof visiteurGuestLayoutLocationRouteImport
      parentRoute: typeof visiteurGuestLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/rendez-vous/': {
      id: '/proprietaire/_proprietaireLayout/rendez-vous/'
      path: '/rendez-vous'
      fullPath: '/proprietaire/rendez-vous'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutRendezVousIndexRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/paiements/': {
      id: '/proprietaire/_proprietaireLayout/paiements/'
      path: '/paiements'
      fullPath: '/proprietaire/paiements'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutPaiementsIndexRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/maisons/': {
      id: '/proprietaire/_proprietaireLayout/maisons/'
      path: '/maisons'
      fullPath: '/proprietaire/maisons'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutMaisonsIndexRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/contrats/': {
      id: '/proprietaire/_proprietaireLayout/contrats/'
      path: '/contrats'
      fullPath: '/proprietaire/contrats'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutContratsIndexRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/chambres/': {
      id: '/proprietaire/_proprietaireLayout/chambres/'
      path: '/chambres'
      fullPath: '/proprietaire/chambres'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutChambresIndexRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/locataire/_locataireLayout/rendez-vous/': {
      id: '/locataire/_locataireLayout/rendez-vous/'
      path: '/rendez-vous'
      fullPath: '/locataire/rendez-vous'
      preLoaderRoute: typeof LocataireLocataireLayoutRendezVousIndexRouteImport
      parentRoute: typeof LocataireLocataireLayoutRoute
    }
    '/locataire/_locataireLayout/contrats/': {
      id: '/locataire/_locataireLayout/contrats/'
      path: '/contrats'
      fullPath: '/locataire/contrats'
      preLoaderRoute: typeof LocataireLocataireLayoutContratsIndexRouteImport
      parentRoute: typeof LocataireLocataireLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/rendez-vous/$rendezVousId/': {
      id: '/proprietaire/_proprietaireLayout/rendez-vous/$rendezVousId/'
      path: '/rendez-vous/$rendezVousId'
      fullPath: '/proprietaire/rendez-vous/$rendezVousId'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutRendezVousRendezVousIdIndexRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/paiements/$paiementId/': {
      id: '/proprietaire/_proprietaireLayout/paiements/$paiementId/'
      path: '/paiements/$paiementId'
      fullPath: '/proprietaire/paiements/$paiementId'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutPaiementsPaiementIdIndexRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/maisons/$maisonId/': {
      id: '/proprietaire/_proprietaireLayout/maisons/$maisonId/'
      path: '/maisons/$maisonId'
      fullPath: '/proprietaire/maisons/$maisonId'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutMaisonsMaisonIdIndexRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/contrats/$contratId/': {
      id: '/proprietaire/_proprietaireLayout/contrats/$contratId/'
      path: '/contrats/$contratId'
      fullPath: '/proprietaire/contrats/$contratId'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutContratsContratIdIndexRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/proprietaire/_proprietaireLayout/chambres/$chambreId/': {
      id: '/proprietaire/_proprietaireLayout/chambres/$chambreId/'
      path: '/chambres/$chambreId'
      fullPath: '/proprietaire/chambres/$chambreId'
      preLoaderRoute: typeof ProprietaireProprietaireLayoutChambresChambreIdIndexRouteImport
      parentRoute: typeof ProprietaireProprietaireLayoutRoute
    }
    '/locataire/_locataireLayout/rendez-vous/$rendezVousId/': {
      id: '/locataire/_locataireLayout/rendez-vous/$rendezVousId/'
      path: '/rendez-vous/$rendezVousId'
      fullPath: '/locataire/rendez-vous/$rendezVousId'
      preLoaderRoute: typeof LocataireLocataireLayoutRendezVousRendezVousIdIndexRouteImport
      parentRoute: typeof LocataireLocataireLayoutRoute
    }
    '/locataire/_locataireLayout/contrats/$contratId/': {
      id: '/locataire/_locataireLayout/contrats/$contratId/'
      path: '/contrats/$contratId'
      fullPath: '/locataire/contrats/$contratId'
      preLoaderRoute: typeof LocataireLocataireLayoutContratsContratIdIndexRouteImport
      parentRoute: typeof LocataireLocataireLayoutRoute
    }
    '/(visiteur)/_guestLayout/chambre/$chambreId/': {
      id: '/(visiteur)/_guestLayout/chambre/$chambreId/'
      path: '/chambre/$chambreId'
      fullPath: '/chambre/$chambreId'
      preLoaderRoute: typeof visiteurGuestLayoutChambreChambreIdIndexRouteImport
      parentRoute: typeof visiteurGuestLayoutRoute
    }
  }
}

interface visiteurGuestLayoutRouteChildren {
  visiteurGuestLayoutLocationRoute: typeof visiteurGuestLayoutLocationRoute
  visiteurGuestLayoutIndexRoute: typeof visiteurGuestLayoutIndexRoute
  visiteurGuestLayoutChambreChambreIdIndexRoute: typeof visiteurGuestLayoutChambreChambreIdIndexRoute
}

const visiteurGuestLayoutRouteChildren: visiteurGuestLayoutRouteChildren = {
  visiteurGuestLayoutLocationRoute: visiteurGuestLayoutLocationRoute,
  visiteurGuestLayoutIndexRoute: visiteurGuestLayoutIndexRoute,
  visiteurGuestLayoutChambreChambreIdIndexRoute:
    visiteurGuestLayoutChambreChambreIdIndexRoute,
}

const visiteurGuestLayoutRouteWithChildren =
  visiteurGuestLayoutRoute._addFileChildren(visiteurGuestLayoutRouteChildren)

interface visiteurRouteChildren {
  visiteurGuestLayoutRoute: typeof visiteurGuestLayoutRouteWithChildren
}

const visiteurRouteChildren: visiteurRouteChildren = {
  visiteurGuestLayoutRoute: visiteurGuestLayoutRouteWithChildren,
}

const visiteurRouteWithChildren = visiteurRoute._addFileChildren(
  visiteurRouteChildren,
)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutLoginRoute: typeof AuthAuthLayoutLoginRoute
  AuthAuthLayoutRegisterRoute: typeof AuthAuthLayoutRegisterRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutLoginRoute: AuthAuthLayoutLoginRoute,
  AuthAuthLayoutRegisterRoute: AuthAuthLayoutRegisterRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LocataireLocataireLayoutRouteChildren {
  LocataireLocataireLayoutDashboardRoute: typeof LocataireLocataireLayoutDashboardRoute
  LocataireLocataireLayoutProfileLazyRoute: typeof LocataireLocataireLayoutProfileLazyRoute
  LocataireLocataireLayoutIndexRoute: typeof LocataireLocataireLayoutIndexRoute
  LocataireLocataireLayoutContratsIndexRoute: typeof LocataireLocataireLayoutContratsIndexRoute
  LocataireLocataireLayoutRendezVousIndexRoute: typeof LocataireLocataireLayoutRendezVousIndexRoute
  LocataireLocataireLayoutContratsContratIdIndexRoute: typeof LocataireLocataireLayoutContratsContratIdIndexRoute
  LocataireLocataireLayoutRendezVousRendezVousIdIndexRoute: typeof LocataireLocataireLayoutRendezVousRendezVousIdIndexRoute
}

const LocataireLocataireLayoutRouteChildren: LocataireLocataireLayoutRouteChildren =
  {
    LocataireLocataireLayoutDashboardRoute:
      LocataireLocataireLayoutDashboardRoute,
    LocataireLocataireLayoutProfileLazyRoute:
      LocataireLocataireLayoutProfileLazyRoute,
    LocataireLocataireLayoutIndexRoute: LocataireLocataireLayoutIndexRoute,
    LocataireLocataireLayoutContratsIndexRoute:
      LocataireLocataireLayoutContratsIndexRoute,
    LocataireLocataireLayoutRendezVousIndexRoute:
      LocataireLocataireLayoutRendezVousIndexRoute,
    LocataireLocataireLayoutContratsContratIdIndexRoute:
      LocataireLocataireLayoutContratsContratIdIndexRoute,
    LocataireLocataireLayoutRendezVousRendezVousIdIndexRoute:
      LocataireLocataireLayoutRendezVousRendezVousIdIndexRoute,
  }

const LocataireLocataireLayoutRouteWithChildren =
  LocataireLocataireLayoutRoute._addFileChildren(
    LocataireLocataireLayoutRouteChildren,
  )

interface LocataireRouteChildren {
  LocataireLocataireLayoutRoute: typeof LocataireLocataireLayoutRouteWithChildren
}

const LocataireRouteChildren: LocataireRouteChildren = {
  LocataireLocataireLayoutRoute: LocataireLocataireLayoutRouteWithChildren,
}

const LocataireRouteWithChildren = LocataireRoute._addFileChildren(
  LocataireRouteChildren,
)

interface ProprietaireProprietaireLayoutRouteChildren {
  ProprietaireProprietaireLayoutDashboardRoute: typeof ProprietaireProprietaireLayoutDashboardRoute
  ProprietaireProprietaireLayoutProfileLazyRoute: typeof ProprietaireProprietaireLayoutProfileLazyRoute
  ProprietaireProprietaireLayoutChambresIndexRoute: typeof ProprietaireProprietaireLayoutChambresIndexRoute
  ProprietaireProprietaireLayoutContratsIndexRoute: typeof ProprietaireProprietaireLayoutContratsIndexRoute
  ProprietaireProprietaireLayoutMaisonsIndexRoute: typeof ProprietaireProprietaireLayoutMaisonsIndexRoute
  ProprietaireProprietaireLayoutPaiementsIndexRoute: typeof ProprietaireProprietaireLayoutPaiementsIndexRoute
  ProprietaireProprietaireLayoutRendezVousIndexRoute: typeof ProprietaireProprietaireLayoutRendezVousIndexRoute
  ProprietaireProprietaireLayoutChambresChambreIdIndexRoute: typeof ProprietaireProprietaireLayoutChambresChambreIdIndexRoute
  ProprietaireProprietaireLayoutContratsContratIdIndexRoute: typeof ProprietaireProprietaireLayoutContratsContratIdIndexRoute
  ProprietaireProprietaireLayoutMaisonsMaisonIdIndexRoute: typeof ProprietaireProprietaireLayoutMaisonsMaisonIdIndexRoute
  ProprietaireProprietaireLayoutPaiementsPaiementIdIndexRoute: typeof ProprietaireProprietaireLayoutPaiementsPaiementIdIndexRoute
  ProprietaireProprietaireLayoutRendezVousRendezVousIdIndexRoute: typeof ProprietaireProprietaireLayoutRendezVousRendezVousIdIndexRoute
}

const ProprietaireProprietaireLayoutRouteChildren: ProprietaireProprietaireLayoutRouteChildren =
  {
    ProprietaireProprietaireLayoutDashboardRoute:
      ProprietaireProprietaireLayoutDashboardRoute,
    ProprietaireProprietaireLayoutProfileLazyRoute:
      ProprietaireProprietaireLayoutProfileLazyRoute,
    ProprietaireProprietaireLayoutChambresIndexRoute:
      ProprietaireProprietaireLayoutChambresIndexRoute,
    ProprietaireProprietaireLayoutContratsIndexRoute:
      ProprietaireProprietaireLayoutContratsIndexRoute,
    ProprietaireProprietaireLayoutMaisonsIndexRoute:
      ProprietaireProprietaireLayoutMaisonsIndexRoute,
    ProprietaireProprietaireLayoutPaiementsIndexRoute:
      ProprietaireProprietaireLayoutPaiementsIndexRoute,
    ProprietaireProprietaireLayoutRendezVousIndexRoute:
      ProprietaireProprietaireLayoutRendezVousIndexRoute,
    ProprietaireProprietaireLayoutChambresChambreIdIndexRoute:
      ProprietaireProprietaireLayoutChambresChambreIdIndexRoute,
    ProprietaireProprietaireLayoutContratsContratIdIndexRoute:
      ProprietaireProprietaireLayoutContratsContratIdIndexRoute,
    ProprietaireProprietaireLayoutMaisonsMaisonIdIndexRoute:
      ProprietaireProprietaireLayoutMaisonsMaisonIdIndexRoute,
    ProprietaireProprietaireLayoutPaiementsPaiementIdIndexRoute:
      ProprietaireProprietaireLayoutPaiementsPaiementIdIndexRoute,
    ProprietaireProprietaireLayoutRendezVousRendezVousIdIndexRoute:
      ProprietaireProprietaireLayoutRendezVousRendezVousIdIndexRoute,
  }

const ProprietaireProprietaireLayoutRouteWithChildren =
  ProprietaireProprietaireLayoutRoute._addFileChildren(
    ProprietaireProprietaireLayoutRouteChildren,
  )

interface ProprietaireRouteChildren {
  ProprietaireProprietaireLayoutRoute: typeof ProprietaireProprietaireLayoutRouteWithChildren
  ProprietaireIndexRoute: typeof ProprietaireIndexRoute
}

const ProprietaireRouteChildren: ProprietaireRouteChildren = {
  ProprietaireProprietaireLayoutRoute:
    ProprietaireProprietaireLayoutRouteWithChildren,
  ProprietaireIndexRoute: ProprietaireIndexRoute,
}

const ProprietaireRouteWithChildren = ProprietaireRoute._addFileChildren(
  ProprietaireRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  visiteurRoute: visiteurRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LocataireRoute: LocataireRouteWithChildren,
  ProprietaireRoute: ProprietaireRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
